[package]
name = "cargo-embed"
version = "0.6.1"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"
description = "A utility to develop software for embedded ARM and RISC-V cores."
documentation = "https://docs.rs/cargo-embed/"
homepage = "https://github.com/probe-rs/cargo-embed"
repository = "https://github.com/probe-rs/cargo-embed"
readme = "README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[dependencies]
structopt = "0.3.2"
cargo-project = "0.2.3"
failure = "0.1.5"
indicatif = "0.14.0"
env_logger = "0.7.1"
log = { version = "0.4.0", features = ["serde"] }
lazy_static = "1.4.0"
colored = "1.8.3"
probe-rs = { version = "0.6.2", git = "https://github.com/probe-rs/probe-rs", branch = "serial-id" }
gdb-server = { version = "0.6.1", git = "https://github.com/probe-rs/probe-rs", branch = "serial-id" }
serde = { version = "1.0", features = ["derive"] }
config = { version = "0.9.0", features = ["toml", "json", "yaml"], default-features = false }
probe-rs-rtt = { version = "0.1.0", git = "https://github.com/probe-rs/probe-rs-rtt", branch = "api-changes" }
chrono = "0.4"

goblin = "0.2.0"
tui = "0.8.0"
termion = "1.5.0"
unicode-width = "0.1.7"
